config/routes.rb
Rails.application.routes.draw do
  get 'donations/new'
  get 'sessions/new'
  get 'signup', to: 'ongs#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :ongs
  resources :sessions
  resources :donations

  root to: 'donations#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :ong
end

app/models/ong.rb
class Ong < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def logged_in?
      @current_user ||= Ong.find(session[:ong_id]) if session[:ong_id]
    end 

    # Matches logged-in user with value.
    def match_login(id)
      session[:ong_id] == id
    end

    def is_admin?
      match_login(1)
    end

    # Confirms a logged-in user.
    def require_login
      unless logged_in?
        redirect_to login_url, notice: 'É necessário realizar login para esta ação.'
      end
    end

    helper_method :logged_in?
    helper_method :is_admin?
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end
  
  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
    @ongs = Ong.where(enabled: true ).where.not(id: 1)
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)
    if @donation.ong.enabled
      respond_to do |format|
        if @donation.save
          format.html { render :show, notice: 'Muito obrigado por sua contribução.' }
          format.json { render :show, status: :created, location: @donation }
        else
          format.html { render :new }
          format.json { render json: @donation.errors, status: :unprocessable_entity }
        end
      end
    else
      format.html { render :new, notice: 'Organização desabilitada.' }
      format.json { render json: @donation.errors, status: :unprocessable_entity }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def donation_params
    params.require(:donation).permit(:ong_id, :amount, :name, :card_number, :expiration)
  end
end

app/controllers/ongs_controller.rb
class OngsController < ApplicationController
  before_action :require_login, only: [:edit, :update, :destroy]
  before_action :set_ong, only: [:show, :edit, :update, :destroy]
  before_action :check_permission, only: [:edit, :update, :destroy]

  # GET /ongs
  # GET /ongs.json
  def index
    @ongs = Ong.all
  end

  # GET /ongs/1
  # GET /ongs/1.json
  def show
  end

  # GET /ongs/new
  def new
    @ong = Ong.new
  end

  # GET /ongs/1/edit
  def edit
  end

  # POST /ongs
  # POST /ongs.json
  def create
    @ong = Ong.new(ong_params)

    respond_to do |format|
      if @ong.save
        format.html { redirect_to @ong, notice: 'Sua organização foi cadastrada com sucesso.' }
        format.json { render :show, status: :created, location: @ong }
      else
        format.html { render :new }
        format.json { render json: @ong.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ongs/1
  # PATCH/PUT /ongs/1.json
  def update
    respond_to do |format|
      if @ong.update(ong_params)
        format.html { redirect_to @ong, notice: 'Os dados de sua organização foram atualizados.' }
        format.json { render :show, status: :ok, location: @ong }
      else
        format.html { render :edit }
        format.json { render json: @ong.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ongs/1
  # DELETE /ongs/1.json
  def destroy
    @ong.destroy
    respond_to do |format|
      format.html { redirect_to ongs_url, notice: 'Organização removida.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ong
      @ong = Ong.find(params[:id])
    end

    # Check if logged user have permission to act on current ong
    def check_permission
      unless match_login(@ong) || is_admin?
        redirect_to login_url, notice: 'Sem permissão suficiente.'
      end
    end

    # Verify input parameters to allow only those below.
    def ong_params
      params.require(:ong).permit(:name, :email, :password, :password_confirmation, :tenant_url, :enabled)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    ong = Ong.find_by(email: params[:email])
    if ong && ong.enabled && ong.authenticate(params[:password])
      session[:ong_id] = ong.id
      redirect_to ongs_path, notice: 'Autenticado!'
    else
      if ong.enabled
        flash.now.alert = 'O e-mail ou a senha estão incorretos.'
      else
        flash.now.alert = 'Organização desabilitada.'
      end
      render :new
    end
  end

  def destroy
    session[:ong_id] = nil
    redirect_to root_url, notice: 'Sessão finalizada!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/ongs_helper.rb
module OngsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/views/donations/_form.html.erb
<%= form_with(model: donation, local: true) do |form| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "erro") %> impediu o processamento da doação:</h2>

      <ul>
      <% donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ong_id %>
    <%= form.select :ong_id, options_for_select(@ongs.collect{ |o| [o.name, o.id] }) %>

  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :card_number %>
    <%= form.text_field :card_number %>
  </div>

  <div class="field">
    <%= form.label :expiration %>
    <%= form.date_field :expiration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doações</h1>

<table>
  <thead>
    <tr>
      <th>Valor</th>
      <th>Doador</th>
      <th>Número do Cartão de Crédito</th>
      <th>Validade do Cartão</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.amount %></td>
        <td><%= donation.name %></td>
        <td><%= donation.card_number %></td>
        <td><%= donation.expiration %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/donations/new.html.erb
<h1>Colabore com nossa causa e faça diferença!</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Voltar', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Obrigado!</h2>

<p>A doação de <%= @donation.amount %> para <%= @donation.ong.name %> foi realizada!</p>

<%= link_to 'Voltar para início', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Implementação teste Trackmob</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="user_header">
      <% if logged_in? %>
        <%= link_to 'Sair', logout_path %>
      <% else %>
        <%= link_to "Acessar", login_path %>
        <%= link_to "Cadastrar Organização", signup_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/ongs/_form.html.erb
<%= form_with(model: ong, local: true) do |form| %>
  <% if ong.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ong.errors.count, "erro") %> impediu salvar dados da organização:</h2>

      <ul>
      <% ong.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :tenant_url %>
    <%= form.text_field :tenant_url %>
  </div>

  <div class="field">
    <%= form.label :enabled %>
    <%= form.check_box :enabled %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ongs/edit.html.erb
<h1>Atualizar dados da organização</h1>

<%= render 'form', ong: @ong %>

<%= link_to 'Mostrar', @ong %> |
<%= link_to 'Voltar', ongs_path %>

app/views/ongs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizações</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>URL</th>
      <th>Habilitado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ongs.each do |ong| %>
      <tr>
        <td><%= ong.name %></td>
        <td><%= ong.email %></td>
        <td><%= ong.tenant_url %></td>
        <td><%= ong.enabled %></td>
        <td><%= link_to 'Mostrar', ong %></td>
        <td><%= link_to 'Editar', edit_ong_path(ong) if logged_in? && ( logged_in?.id == ong.id || is_admin? ) %></td>
        <td><%= link_to 'Remover', ong, method: :delete, data: { confirm: 'Tem certeza que deseja remover?' } if logged_in? && ( logged_in?.id == ong.id || is_admin? ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova organização', new_ong_path %>

app/views/ongs/new.html.erb
<h1>Cadastre-se</h1>

<%= render 'form', ong: @ong %>

<%= link_to 'Voltar', ongs_path %>

app/views/ongs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @ong.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @ong.email %>
</p>

<p>
  <strong>URL:</strong>
  <%= @ong.tenant_url %>
</p>

<p>
  <strong>Habilitado:</strong>
  <%= @ong.enabled %>
</p>

<%= link_to 'Editar', edit_ong_path(@ong) %> |
<%= link_to 'Voltar', ongs_path %>